
# https://taskfile.dev

version: '3'

includes:
  husk:
    flatten: true
    taskfile: ./husky.Taskfile.yml

vars:
  GREETING: Hello, World!

tasks:
  statedev: 
    cmds:
      - echo "# SYNC STATUS" > ./docs/devlog/sync-status.md
      - echo " > `timestamp = $( date +%s )`" >> ./docs/devlog/sync-status.md
      - echo "---" >> ./docs/devlog/sync-status.md
      - echo "```md" >> ./docs/devlog/sync-status.md
      - gh repo view >> ./docs/devlog/sync-status.md
      - echo "```" >> ./docs/devlog/sync-status.md
      - echo "---" >> ./docs/devlog/sync-status.md
      - git status >> ./docs/devlog/sync-status.md
      - echo "---" >> ./docs/devlog/sync-status.md
      - git submodule status  >> ./docs/devlog/sync-status.md
      - echo "---" >> ./docs/devlog/sync-status.md
      - git submodule foreach git status >> ./docs/devlog/sync-status.md
      - echo "---" >> ./docs/devlog/sync-status.md
      - echo "```" >> ./docs/devlog/sync-status.md
      - git log >> ./docs/devlog/sync-status.md
      - echo "```" >> ./docs/devlog/sync-status.md
      - echo " > `timestamp = $( date +%s )`" >> ./docs/devlog/sync-status.md
  
  lazysync:
    cmds:
      # - git fetch
      # - git submodule foreach git fetch
      # - git pull
      # - git submodule foreach git pull
      - git fetch
      - git pull
      - touch I_AM_LAZY_$( date +%s )
      #- echo "TASK ROUTINES:LAZYSYNC  with timestamp = $( date +%s )" > I_AM_LAZY
      - git add .
      - git commit -m "autosync timestamp = $( date +%s )" 2>/dev/null
      - git push
      - git submodule foreach git fetch
      - git submodule foreach git pull
      - git submodule foreach touch I_AM_LAZY_$( date +%s )
      #- git submodule foreach wget https://api.github.com/zen
      #- git submodule foreach echo "TASK ROUTINES:LAZYSYNC  with timestamp = $( date +%s )" > I_AM_LAZY
      - git submodule foreach git add .
      - git submodule foreach git commit -m "submodules autosync with timestamp = $( date +%s )" 2>/dev/null
      - git submodule foreach git push
      - git add .
      - git commit -m "cumulation of syncing by lazysync routine task, timestamp = $( date +%s )" 2>/dev/null
      - git push
  default:
    cmds:
      - npm i
      - npm i -D
      - task --list-all
    silent: true
  
  

# python -c 'import toml ; [print("echo \"task routines:\\\$(basename \\\$0 )\" > ./.husky/"+x) for x in toml.load(".husky/.omnis.toml")["HUSKY_SCRIPTS"]]' | sh
